// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Human interface {
	IsHuman()
}

type Person interface {
	IsPerson()
}

type Cuctomer struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Pii  *Pii   `json:"pii"`
}

func (Cuctomer) IsHuman()  {}
func (Cuctomer) IsPerson() {}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Pii struct {
	ID       string `json:"id"`
	Pii      string `json:"pii"`
	SuperPii string `json:"superPii"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type Role string

const (
	RoleSuperAdmin Role = "SUPER_ADMIN"
	RoleAdmin      Role = "ADMIN"
	RoleOwner      Role = "OWNER"
)

var AllRole = []Role{
	RoleSuperAdmin,
	RoleAdmin,
	RoleOwner,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleSuperAdmin, RoleAdmin, RoleOwner:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
